superloc/manager/urls.py
from django.contrib.auth import views as auth_views
from django.core.exceptions import PermissionDenied
from django.urls import path

from . import views

app_name = 'manager'

def permission_denied_view(request):
    raise PermissionDenied

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.LoginManager.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('403', permission_denied_view, name='forbidden'),    
    path('vehicles_availability_form', views.vehicles_availability_form, name='vehicles_availability_form'),
    path('vehicles_availability/<str:id>', views.vehicles_availability, name='vehicles_availability'),
    path('booking', views.booking, name='booking'),
    path('vehicles_management_agency_choice', views.vehicles_management_agency_choice, name='vehicles_management_agency_choice'),
    path('vehicles_management/<str:id>', views.vehicles_management, name='vehicles_management'),
    path('vehicles_management/vehicle_add/<str:id>', views.vehicle_add, name='vehicle_add'),
    path('vehicles_management/vehicle_delete/<str:id>', views.vehicle_delete, name='vehicle_delete'),
]

superloc/superloc/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from . import views,settings

urlpatterns = [
    path('', views.home),
    path('visitor/', include('visitor.urls')),
    path('manager/', include('manager.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

superloc/visitor/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name='visitor'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('legal_notice', views.legal_notice, name = 'legal_notice'),
    path('tourism/categories', views.tourism_categories, name = 'tourism_categories'),
    path('tourism/categories/<str:code>', views.tourism_category, name = 'tourism_category'),
    path('TODO', views.todo, name= 'todo'),
    path('login/', auth_views.LoginView.as_view(), name= 'login'),
    path('logout/', auth_views.LogoutView.as_view(), {'next_page': 'home'}, name='logout'),
    path('inscription', views.inscription, name= 'inscription'),
    path('customer/edit', views.edit_customer, name='edit_customer'),
    path('language_choice', views.language_choice, name= 'language_choice'),
    path('agencies', views.agencies, name= 'agencies'),
    path('booking_management', views.booking_management, name= 'booking_management'),
    path('reservation', views.reservation, name='reservation'),
    path('reservation_vehicle_choice', views.reservation_vehicle_choice, name='reservation_vehicle_choice'),
    ]

superloc/manager/models.py
from django.db import models

# Create your models here.

superloc/manager/forms.py
from django.forms import ModelForm
from django import forms
from datetime import datetime
from django.core.exceptions import ValidationError

from visitor.models import Category, Vehicle, Agency, Booking

def get_agencies():
    agencies = Agency.objects.filter(is_active=True)
    return tuple(list(agencies.values_list('id', 'name')))

class GetAgencyForm(ModelForm) :
    class Meta:
        model = Agency
        fields = ['name']
        labels = {'name': ('Agence')}
        widgets = {'name': forms.Select(choices=get_agencies())}

def get_categories():
    categories = Category.objects.filter(is_active=True)
    return tuple(list(categories.values_list('id', 'code')))

class VehicleAddForm(forms.ModelForm):
    class Meta:
        model = Vehicle
        fields = ('category', 'manufacturer', 'car_model', 'registration_number', 'vehicle_identification_number')
        labels = {'category': ('Catégorie'), 'vehicle_identification_number': ("Numéro d'identification du véhicule (VIN)")}
        widgets = {'category': forms.Select(choices=get_categories())}

class AvailabilityForm(forms.Form):
    DATE_FORMAT = '%Y-%m-%dT%H:%M'
    agency = forms.ModelChoiceField(label='Agence', queryset=Agency.objects.filter(is_active=True), required=True)
    category = forms.ModelChoiceField(label='Catégorie', queryset=Category.objects.filter(is_active=True), required=True)
    date_departure = forms.DateTimeField(label='Date de départ',    
                                         input_formats = [DATE_FORMAT],
                                         widget = forms.DateTimeInput(
                                             attrs = {'type': 'datetime-local', },
                                             format = DATE_FORMAT, ),
                                         required = True,
                                         )
    date_back = forms.DateTimeField(label='Date de retour',
                                    input_formats = [DATE_FORMAT],
                                    widget = forms.DateTimeInput(
                                        attrs = {'type': 'datetime-local', },
                                        format = DATE_FORMAT, ),
                                    required = True,
                                    )

superloc/manager/views.py
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
from django.http import Http404, HttpResponse
from visitor.models import Category, Vehicle, Booking, Agency, vehicle_availability_list
from .forms import GetAgencyForm, VehicleAddForm, AvailabilityForm


class LoginManager(LoginView):
    template_name = 'manager/login.html'

def role_check(user):
    return user.groups.filter(name='manager').exists()

def logged_out(request):
    return render(request, 'manager/logged_out.html')

@login_required(login_url='manager:login')
@user_passes_test(role_check, login_url='manager:forbidden')
def home(request):
    return render(request, 'manager/index.html')

@login_required(login_url='manager:login')
def vehicles_availability_form(request):
    if request.method == 'POST':
        form = AvailabilityForm(request.POST)
        if form.is_valid():        
            agency_id = request.POST.get('agency')
            category_id = request.POST.get('category')
            date_departure = request.POST.get('date_departure')
            date_back= request.POST.get('date_back')
            agency_departure = Agency.objects.get(id=agency_id)
            category = Category.objects.get(id=category_id)
            vehicle_list=vehicle_availability_list(category, agency_departure, date_departure, date_back)
            date_departure_day = date_departure[8:10]
            date_departure_month = date_departure[5:7]
            date_departure_year = date_departure[0:4]
            date_departure_time = date_departure[11:]
            date_back_day = date_back[8:10]
            date_back_month = date_back[5:7]
            date_back_year = date_back[0:4]
            date_back_time = date_back[11:]
            if date_back<date_departure:
                return HttpResponse('La date de retour doit être postérieure à la date de départ.')
            else:
                context = {'agency':agency_departure,
                            'vehicle_list':vehicle_list,
                            'date_departure':date_departure,
                            'date_back':date_back,
                            'date_departure_day':date_departure_day,
                            'date_departure_month':date_departure_month,
                            'date_departure_year':date_departure_year,
                            'date_departure_time':date_departure_time,
                            'date_back_day':date_back_day,
                            'date_back_month':date_back_month,
                            'date_back_year':date_back_year,
                            'date_back_time':date_back_time,
                }       
            return render(request, 'manager/vehicles_availability.html', context)
    availability_form=AvailabilityForm()
    context = {'form': availability_form}
    return render(request, 'manager/vehicles_availability_form.html', context)

@login_required(login_url='manager:login')
def vehicles_availability(request, id) :
    try:
        agency = Agency.objects.get(id__exact=id.upper())
    except Agency.DoesNotExist:
        raise Http404
    vehicle = Vehicle.objects.filter(is_active=True, agency_id=agency.id)
    context = {'vehicle_list' : vehicle,
               'agency': agency
               }
    return render(request, 'manager/vehicles_availability.html', context)

@login_required(login_url='manager:login')
def booking(request):
    return render(request, 'manager/booking.html')

@login_required(login_url='manager:login')
def vehicles_management_agency_choice(request):
    if request.method == 'POST':
        agency = request.POST.get('name')
        return redirect('manager:vehicles_management', agency)
    get_agency_form = GetAgencyForm()
    context = {'form': get_agency_form}
    return render(request, 'manager/vehicles_management_agency_choice.html', context)

@login_required(login_url='manager:login')
def vehicles_management(request, id) :
    try:
        agency = Agency.objects.get(id__exact=id.upper())
    except Agency.DoesNotExist:
        raise Http404
    vehicle = Vehicle.objects.filter(is_active=True, agency_id=agency.id)
    context = {'vehicle_list' : vehicle,
               'agency': agency
               }
    return render(request, 'manager/vehicles_management.html', context)

@login_required(login_url='manager:login')
@permission_required('visitor.change_vehicle', raise_exception=True)
def vehicle_delete(request, id) :
    try:
        vehicle = Vehicle.objects.get(id__exact=id.upper())
    except Vehicle.DoesNotExist:
        raise Http404
    if request.method == 'POST':
        vehicle=Vehicle.objects.get(id=id)
        vehicle.is_active = False
        vehicle.save()
        agency=Agency.objects.get(id=vehicle.agency_id)
        agency_nbr=agency.id
        return redirect(f'/manager/vehicles_management/{agency_nbr}')
    return render(request, 'manager/vehicle_delete.html', {'vehicle': vehicle})

@login_required(login_url='manager:login')
@permission_required('visitor.change_vehicle', raise_exception=True)
def vehicle_add(request,id):
    try:
        agency = Agency.objects.get(id__exact=id.upper())
    except Agency.DoesNotExist:
        raise Http404
    if request.method == 'POST':
        vehicle = Vehicle(agency=agency)
        form= VehicleAddForm(request.POST, instance=vehicle)
        if form.is_valid():
            vehicle=form.save()
            agency = Agency.objects.get(id=vehicle.agency_id)
            agency_nbr = agency.id
            return redirect(f'/manager/vehicles_management/{agency_nbr}')
    else:
        form = VehicleAddForm()
    context = {'form': form,'agency': agency}
    return render(request, 'manager/vehicle_add.html', context)

superloc/manager/templates/manager/base.html
<!doctype html>
<html lang="fr">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <title>{% block title %}SUPERLOC | Manager{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'visitor/style.css' %}" />
    </head>
<body>
    <header class=banner>
        <div id="logo">
            <a href="{% url 'visitor:home' %}" title="Accueil">
            <img src="{% static 'visitor/images/logo.png' %}" alt="logo"></a>
        </div>
        <div id="contact_manager">
        </div>
        <div id="menu_name">
            <div id="company_name">
                <b>SUPERLOC</b>
            </div>
            <nav id="menu">
                <ul>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                </ul>
            </nav>
        </div>
        <div id="configuration">
            <div id="log">
                {% if request.user.is_authenticated %}
                    {{ request.user.first_name }} {{ request.user.last_name }}</br>
                    <a href="{% url 'visitor:logout' %}?next={{ request.path }}">Se déconnecter</a>
                {% endif %}
            </div>
            <div id="language">
                <a href="{% url 'visitor:language_choice' %}"><b>FR</b></a>
            </div>
            <div id=calendar_clock>
                <div id="clock">
                    {% now "H:i" %}
                </div>
                <div id="calendar">
                    {% now "l j F Y" %}
                </div>
            </div>
        </div>
    </header>
        {% block content %}{% endblock %}
</body>
</html>

superloc/manager/templates/manager/booking.html
{% extends "manager/base.html" %}

{% block title %}SUPERLOC | Disponibilité des véhicules{% endblock %}

{% block content %}
<div>
    <h1>Disponibilité des véhicules</h1>
    <p>Agence de <b>{{agency.name}}</b></p>
    <form action="" method="post">
        {%csrf_token%}
        <p>Choisissez un client</p>
        <p>Véhicule {{vehicle.manufacturer}} {{vehicle.car_model}} immatriculé {{vehicle.registration_number}}</p>
        <p>Réservation du <b>{{date_departure_day}}/{{date_departure_month}}/{{date_departure_year}}</b> à <b>{{date_departure_time}}</b> au <b>{{date_back_day}}/{{date_back_month}}/{{date_back_year}}</b> à <b>{{date_back_time}}</b></p>

        




        <input type="submit" value="Confirmer la réservation">
  </form>
{% endblock %}

superloc/manager/templates/manager/index.html
{% extends "manager/base.html" %}

{% block title %}SUPERLOC | Manager{% endblock %}

{% block content %}
<div>
    <h1>Manager</h1>
    <p><a href="{% url 'manager:vehicles_availability_form' %}">Consultation de la disponibilité des véhicules</a></p>
    <p><a href="{% url 'manager:vehicles_management_agency_choice' %}">Gestion des véhicules</a></p>
    <p>Gestion des réservations</p>
</div>
{% endblock %}

superloc/manager/templates/manager/logged_out.html
{% extends 'manager/base.html' %}

{% block title %}SUPERLOC | Manager{% endblock %}

{% block content %}
    <div>
        <h1>Veuillez vous <a href="{% url 'manager:login' %}?next={% url 'manager:home' %}">connecter</a>pour accéder aux pages gestionnaire</h1>
    </div>
{% endblock %}

superloc/manager/templates/manager/login.html
{% extends 'manager/base.html' %}

{% block title %}SUPERLOC | Login manager{% endblock %}

{% block content %}
<div>
    <h1>Login manager</h1>
    <form action="{% url 'manager:login' %}" method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Se connecter"></p>
        <input type="hidden" name="next" value="{{ next }}"/>
        <p>Pas de compte ? Contactez votre administrateur.</p>
    </form>
</div>
{% endblock %}

superloc/manager/templates/manager/vehicle_add.html
{% extends "manager/base.html" %}

{% block title %}SUPERLOC | Gestion des véhicules{% endblock %}

{% block content %}
<div>
  <h1>Gestion des véhicules</h1>
  <p>Agence de <b>{{agency.name}}</b></p>
  <form action="" method="post">
    {%csrf_token%}
    {{ form.as_p }}
    <input type="submit" value="Ajouter le véhicule">
  </form>
</div>
{% endblock %}

superloc/manager/templates/manager/vehicle_delete.html
{% extends "manager/base.html" %}

{% block title %}SUPERLOC | Gestion des véhicules{% endblock %}

{% block content %}
<div>
    <h1>Gestion des véhicules</h1>
    <p>Etes-vous certain de vouloir supprimer le véhicule suivant ?</p>
    <p>{{vehicle.manufacturer}} <b>{{vehicle.car_model}}</b> immatriculé <b>{{vehicle.registration_number}}</b></p>
    <form action="" method="post">
        {%csrf_token%}
        <input type="submit" value="Supprimer ce véhicule">
    </form>
</div>
{% endblock %}

superloc/manager/templates/manager/vehicles_availability.html
{% extends "manager/base.html" %}

{% block title %}SUPERLOC | Disponibilité des véhicules{% endblock %}

{% block content %}
<div>
    <h1>Disponibilité des véhicules</h1>
    <p>Agence de <b>{{agency.name}}</b></p>
    <p>Réservation du <b>{{date_departure_day}}/{{date_departure_month}}/{{date_departure_year}}</b> à <b>{{date_departure_time}}</b> au <b>{{date_back_day}}/{{date_back_month}}/{{date_back_year}}</b> à <b>{{date_back_time}}</b></p>
    <table id="manager_table">
        <tr id="manager_table">
            <th id="column_manager_table">
                Catégorie
            </th>
            <th id="column_manager_table">
                Marque
            </th>
            <th id="column_manager_table">
                Modèle
            </th>
            <th id="column_manager_table">
                Immatriculation
            </th>
        </tr>
        {% for vehicle in vehicle_list %}
        <tr>
            <td id="column_manager_table">
                {{vehicle.category.code}} - {{vehicle.category.label}}
            </td>
            <td id="column_manager_table">
                {{vehicle.manufacturer}}
            </td>
            <td id="column_manager_table">
                {{vehicle.car_model}}
            </td>
            <td id="column_manager_table">
                {{vehicle.registration_number}}
            </td>
            <td>
                <a href="{% url 'manager:booking' %}">Réserver ce véhicule</a>
            </td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}

superloc/manager/templates/manager/vehicles_availability_form.html
{% extends "manager/base.html" %}

{% block title %}SUPERLOC | Disponibilité des véhicules{% endblock %}

{% block content %}
<div>
  <h1>Disponibilité des véhicules</h1>
  <form action="{% url 'manager:vehicles_availability_form' %}" method="post">
    {%csrf_token%}
    {{ form.as_p }}
    <input type="submit" value="Consulter les disponibilités">
  </form>
</div>
{% endblock %}

superloc/manager/templates/manager/vehicles_management.html
{% extends "manager/base.html" %}

{% block title %}SUPERLOC | Gestion des véhicules{% endblock %}

{% block content %}
<div>
    <h1>Gestion des véhicules</h1>
    <p>Agence de <b>{{agency.name}}</b></p>
    <table id="manager_table">
        <tr>
            <th id="column_manager_table">
                Catégorie
            </th>
            <th id="column_manager_table">
                Marque
            <th id="column_manager_table">
                Modèle
            </th>
            <th id="column_manager_table">
                Immatriculation
            </th>
            <th>
            </th>
        </tr>
        {% for vehicle in vehicle_list %}
        <tr>
            <td id="column_manager_table">
                {{vehicle.category.code}} - {{vehicle.category.label}}
            </td>
            <td id="column_manager_table">
                {{vehicle.manufacturer}}
            </td>
            <td id="column_manager_table">
                {{vehicle.car_model}}
            </td>
            <td id="column_manager_table">
                {{vehicle.registration_number}}
            </td>
            <td>
                <a href="{% url 'manager:vehicle_delete' vehicle.id %}">Supprimer ce véhicule</a>
            </td>
        </tr>
        {% endfor %}
    </table>
    <p>
        <a href="{% url 'manager:vehicle_add' agency.id %}">Ajouter un véhicule</a>
    </p>
</div>
{% endblock %}

superloc/manager/templates/manager/vehicles_management_agency_choice.html
{% extends "manager/base.html" %}

{% block title %}SUPERLOC | Gestion des véhicules{% endblock %}

{% block content %}
</div>
  <h1>Gestion des véhicules</h1>
  <form action="{% url 'manager:vehicles_management_agency_choice' %}" method="post">
    {%csrf_token%}
    {{ form.as_p }}
    <input type="submit" value="Gérer les véhicules">
  </form>
</div>
{% endblock %}