superloc/manager/urls.py
from django.contrib.auth import views as auth_views
from django.core.exceptions import PermissionDenied
from django.urls import path

from . import views

app_name = 'manager'

def permission_denied_view(request):
    raise PermissionDenied

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.LoginManager.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('403', permission_denied_view, name='forbidden'),    
    path('vehicles_availability_form', views.vehicles_availability_form, name='vehicles_availability_form'),
    path('vehicles_availability/<str:id>', views.vehicles_availability, name='vehicles_availability'),
    path('booking', views.booking, name='booking'),
    path('vehicles_management_agency_choice', views.vehicles_management_agency_choice, name='vehicles_management_agency_choice'),
    path('vehicles_management/<str:id>', views.vehicles_management, name='vehicles_management'),
    path('vehicles_management/vehicle_add/<str:id>', views.vehicle_add, name='vehicle_add'),
    path('vehicles_management/vehicle_delete/<str:id>', views.vehicle_delete, name='vehicle_delete'),
]

superloc/superloc/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include

from . import views,settings

urlpatterns = [
    path('', views.home),
    path('visitor/', include('visitor.urls')),
    path('manager/', include('manager.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

superloc/visitor/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name='visitor'

urlpatterns = [
    path('', views.home, name = 'home'),
    path('legal_notice', views.legal_notice, name = 'legal_notice'),
    path('tourism/categories', views.tourism_categories, name = 'tourism_categories'),
    path('tourism/categories/<str:code>', views.tourism_category, name = 'tourism_category'),
    path('TODO', views.todo, name= 'todo'),
    path('login/', auth_views.LoginView.as_view(), name= 'login'),
    path('logout/', auth_views.LogoutView.as_view(), {'next_page': 'home'}, name='logout'),
    path('inscription', views.inscription, name= 'inscription'),
    path('customer/edit', views.edit_customer, name='edit_customer'),
    path('language_choice', views.language_choice, name= 'language_choice'),
    path('agencies', views.agencies, name= 'agencies'),
    path('booking_management', views.booking_management, name= 'booking_management'),
    path('reservation', views.reservation, name='reservation'),
    path('reservation_vehicle_choice', views.reservation_vehicle_choice, name='reservation_vehicle_choice'),
    ]

superloc/visitor/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User

GEARS_CHOICES = (
    ('M', 'Manuelle'),
    ('A', 'Automatique'),
    ('MA', 'Manuelle ou Automatique')
)

ENERGY_CHOICES = (
    ('G', 'Essence'),
    ('D', 'Diesel'),
    ('GD', 'Essence ou Diesel'),
    ('E', 'Electrique'),
    ('H', 'Hybride')
)

class Category(models.Model):
    code = models.CharField(max_length=1, unique=True)
    label = models.CharField('Nom de la catégorie', max_length=30)
    sample = models.CharField('Modèle principal', max_length=30)
    image = models.ImageField(upload_to='category', max_length=300)
    description = models.TextField(null=True)
    nb_seats = models.IntegerField('Nombre de places', default=5)
    nb_luggage = models.IntegerField('Nombre de bagages', default=0)
    nb_doors = models.IntegerField('Nombre de portes', default=5)
    gear = models.CharField('Type de boite', max_length=2, choices=GEARS_CHOICES, default='MA')
    energy = models.CharField('Energie', max_length=2, choices=ENERGY_CHOICES, default='GD')
    climate_control = models.BooleanField('Climatisation', default=True)
    winter = models.BooleanField('Equipé hiver', default=False)
    pre_pay = models.DecimalField('Montant du pré-paiement', decimal_places=2, max_digits=10, default=0)
    equivalent = models.TextField('Modèles équivalents', null=True)
    is_active = models.BooleanField('Actif', default=True)

    class Meta:
        verbose_name = 'Catégories de véhicule'
        ordering = ['code']

    def __str__(self):
        return 'Catégorie {} - {} - {}'.format(self.code, self.label, self.sample)

class Agency(models.Model):
    name = models.CharField('Nom', max_length=100, unique=True)
    address = models.CharField('Adresse', max_length=100)
    zip_code = models.CharField('Code postal', max_length=5)
    city = models.CharField('Ville', max_length=50)
    phone = models.CharField('Téléphone', max_length=10)
    email = models.CharField('E-mail', max_length=50, unique=True)
    is_active = models.BooleanField('Actif', default=True)

    class Meta:
        verbose_name = 'Agences de location'
        ordering = ['name']

    def __str__(self):
        return '{} - {}'.format(self.name, self.city)

class Vehicle(models.Model):
    manufacturer = models.CharField('Constructeur', max_length=50)
    car_model = models.CharField('Modèle', max_length=50, null=True)
    registration_number = models.CharField('Immatriculation', max_length=9, unique=True, validators=[RegexValidator(regex=r'^[A-Z]{2}-\d{3}-[A-Z]{2}$', message='Immatriculation invalide ! Le format attendu est AA-000-AA.')])
    vehicle_identification_number = models.CharField('VIN', max_length=17, unique=True)
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    agency = models.ForeignKey(Agency, on_delete=models.PROTECT)
    is_active = models.BooleanField('Actif', default=True)

    class Meta:
        verbose_name = 'Véhicule'
        ordering = ['manufacturer', 'car_model', 'registration_number']

    def __str__(self):
        return '{} - {} - {}'.format(self.manufacturer, self.car_model, self.registration_number)

CLIENT_CHOICES = (
    ('PRI', 'Particulier'),
    ('PRO', 'Professionnel'),
)

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    client_type = models.CharField('Type de client', max_length=3, choices=CLIENT_CHOICES, default='PRI')
    date_of_birth = models.DateField('Date de naissance', null=True)
    address = models.CharField('Adresse', max_length=100, null=True)
    zipcode = models.CharField('Code postal', max_length=5, null=True)
    city = models.CharField('Ville', max_length=50, null=True)
    phone = models.CharField('Téléphone', max_length=10, null=True)
    licence_scan = models.ImageField('Copie permis de conduire', upload_to='customer_licences', blank=True)
    licence_number = models.CharField('Numéro du permis de conduire', max_length=12, null=True)
    receiveAdds = models.BooleanField('Accepte de recevoir de la publicité ?', default=True)
    creditCardNumber = models.CharField('Numéro de carte de paiement', max_length=16, null=True)
    creditCardValidity = models.DateField('Fin de validité de la carte de paiement', null=True)

    def __str__(self):
        return f'Customer {self.user.username}'

class Booking(models.Model):
    vehicle = models.ForeignKey(Vehicle, on_delete=models.PROTECT)
    agency = models.ForeignKey(Agency, on_delete=models.PROTECT)
    customer = models.ForeignKey(Customer, on_delete=models.PROTECT)
    date_start = models.DateTimeField('Date de début de location')
    date_end = models.DateTimeField('Date de fin de location')
    confirm = models.BooleanField(default=False)

def vehicle_availability_list(category, agency_departure, date_departure, date_back):
    bookings_to_exclude_list = (
        Booking.objects.all()
            .filter(agency=agency_departure)
            #.filter(date_end__gte=date_departure, date_start__lte=date_departure)
            .filter(date_start__lte=date_back, date_end__gte=date_departure)
    )
    available_vehicles = (
        Vehicle.objects.all()
            .filter(is_active=True)
            .filter(agency=agency_departure)
            .filter(category=category)
            .exclude(id__in=(bookings_to_exclude_list.values('vehicle')))
    )
    return available_vehicles

superloc/visitor/views.py
from django.shortcuts import render, redirect
from django.http import Http404
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from visitor.models import Category, Agency, Customer, Booking, Vehicle, vehicle_availability_list
from visitor.forms import UserRegistrationForm, UserEditForm, CustomerEditForm, BookingForm

def home(request):
    return render(request, 'visitor/index.html')

def legal_notice(request) :
    return render(request, 'visitor/legal_notice.html')

def todo(request) :
    return render(request, 'visitor/todo.html')

def language_choice(request) :
    return render(request, 'visitor/language_choice.html')

def login(request) :
    return render(request, 'registration/login.html')

def tourism_categories(request):
    categories = Category.objects.filter(is_active=True)
    context = {'category_list' : categories}
    return render(request, 'visitor/tourism_categories.html', context)

def tourism_category(request, code):
    try:
        category = Category.objects.get(code__exact=code.upper())
    except Category.DoesNotExist:
        raise Http404
    return render(request,'visitor/tourism_category.html', {'category': category})

def agencies(request):
    agencies = Agency.objects.filter(is_active=True)
    context = {'agency_list' : agencies}
    return render(request, 'visitor/agencies.html', context)

def inscription(request):
    next_page = request.GET.get('next', '')
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        customer_form = CustomerEditForm(request.POST)
        if user_form.is_valid() and customer_form.is_valid() :
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.username = new_user.email
            new_user.save()
            Customer.objects.create(user=new_user)
            customer_form.save()
            return render(request, 'registration/inscription_done.html',
                          {'new_user': new_user, 'next': next_page})
        else:
            messages.error(request, "Error")
            return render(request, 'registration/inscription.html',
                          {'user_form': user_form, 'customer_form': customer_form, 'next': next_page})
    else:
        user_form = UserRegistrationForm()
        customer_form = CustomerEditForm()
        return render(request, 'registration/inscription.html',
                      {'user_form': user_form, 'customer_form': customer_form, 'next': next_page})


@login_required
def edit_customer(request):
    if request.method == 'POST':
        user_form = UserEditForm(request.POST, instance=request.user)
        customer_form = CustomerEditForm(request.POST, instance=request.user.customer, files=request.FILES)
        if user_form.is_valid() and customer_form.is_valid():
            user_form.save()
            customer_form.save()
            next_page = request.GET.get('next')
            return redirect(next_page)
    else:
        user_form = UserEditForm(instance=request.user)
        customer_form = CustomerEditForm(instance=request.user.customer)
        next_page = request.GET.get('next')
        return render(request, 'visitor/edit_customer.html',
                      {'user_form': user_form, 'customer_form': customer_form, 'next': next_page})

@login_required
def reservation(request):
    if request.method == 'POST':
        booking_form = BookingForm(request.POST)
        if booking_form.is_valid():
            agency_id = request.POST.get('agency')
            category_id = request.POST.get('category')
            date_departure = request.POST.get('date_departure')
            date_back= request.POST.get('date_back')
            agency_departure = Agency.objects.get(id=agency_id)
            category = Category.objects.get(id=category_id)
            vehicle_list=vehicle_availability_list(category, agency_departure, date_departure, date_back)
            date_departure_day = date_departure[8:10]
            date_departure_month = date_departure[5:7]
            date_departure_year = date_departure[0:4]
            date_departure_time = date_departure[11:]
            date_back_day = date_back[8:10]
            date_back_month = date_back[5:7]
            date_back_year = date_back[0:4]
            date_back_time = date_back[11:]
            context = {'agency':agency_departure,
                       'vehicle_list':vehicle_list,
                       'date_departure':date_departure,
                       'date_back':date_back,
                       'date_departure_day':date_departure_day,
                       'date_departure_month':date_departure_month,
                       'date_departure_year':date_departure_year,
                       'date_departure_time':date_departure_time,
                       'date_back_day':date_back_day,
                       'date_back_month':date_back_month,
                       'date_back_year':date_back_year,
                       'date_back_time':date_back_time,
                       }
            return render(request, 'visitor/reservation_vehicle_choice.html', context)
    booking_form=BookingForm()
    context = {'form': booking_form}
    return render(request, 'visitor/reservation.html', context)

def reservation_vehicle_choice(request) :
    if request.method == 'POST':
        booking_vehicle = request.POST.get('car')
        agency_departure = request.POST.get('agency')
        date_departure= request.POST.get('date_departure')
        date_back = request.POST.get('date_back')
        vehicle = Vehicle.objects.get(registration_number=booking_vehicle)
        agency = Agency.objects.get(id=agency_departure)
        customer = Customer.objects.get(user_id=request.user.id)
        booking = Booking(vehicle=vehicle,
                          date_start=date_departure,
                          date_end=date_back,
                          agency=agency,
                          customer=customer,
                          confirm=True)
        booking.save()
        date_departure_day = date_departure[8:10]
        date_departure_month = date_departure[5:7]
        date_departure_year = date_departure[0:4]
        date_departure_time = date_departure[11:]
        date_back_day = date_back[8:10]
        date_back_month = date_back[5:7]
        date_back_year = date_back[0:4]
        date_back_time = date_back[11:]
        context = {'agency': agency,
                   'booking':booking,
                   'vehicle': vehicle,
                   'date_departure': date_departure,
                   'date_back': date_back,
                   'date_departure_day': date_departure_day,
                   'date_departure_month': date_departure_month,
                   'date_departure_year': date_departure_year,
                   'date_departure_time': date_departure_time,
                   'date_back_day': date_back_day,
                   'date_back_month': date_back_month,
                   'date_back_year': date_back_year,
                   'date_back_time': date_back_time,
                   }
        return render(request, 'visitor/index.html', context)
    return render(request, 'visitor/reservation_confirmation')

@login_required(login_url='visitor:login')
def booking_management(request):
    user=request.user
    customer=Customer.objects.get(user_id=user.id)
    booking_list=Booking.objects.filter(customer_id=customer.id)
    context = {'booking_list': booking_list, 'user' : user}
    return render(request, 'visitor/booking_management.html', context)

superloc/visitor/templates/visitor/agencies.html
{% extends "./base.html" %}

{% load static %}

{% block title %}Nos agences{% endblock %}

{% block content %}
<div id="display_agencies">
    <h1>Nos agences</h1>
    <div id="agencies_strip">
        <div id="agencies">
            {% for agency in agency_list %}
            <div id="agency">
                <p><b>{{agency.name}}</b></p>
                <p>{{agency.address}}<br>{{agency.zip_code}} {{agency.city}}</p>
                <p>{{agency.phone}}</p>
                <p><a href="mailto:{{agency.email}}">Contacter cette agence</a></p>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

superloc/visitor/templates/visitor/base.html
<!doctype html>
<html lang="fr">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <title>{% block title %}SUPERLOC | Location de véhicules de tourisme et utilitaires{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'visitor/style.css' %}" />
    </head>
<body>
    <header class=banner>
        <div id="logo">
            <a href="{% url 'visitor:home' %}" title="Accueil">
            <img src="{% static 'visitor/images/logo.png' %}" alt="logo"></a>
        </div>
        <div id="contact">
            Contactez-nous<br>
            au<br>
            <strong>0 810 24 24 24</strong><br>
            gratuit<br>
            + prix appel
        </div>
        <div id="menu_name">
            <div id="company_name">
                <b>SUPERLOC</b>
            </div>
            <nav id="menu">
                <ul>
                    <li><a href="{% url 'visitor:tourism_categories' %}"><b>Catalogue</b></a></li>
                    <li>{% if request.user.is_authenticated %}
                            <a href="{% url 'visitor:edit_customer' %}?next={{ request.path }}"><b>Espace particuliers</b></a>
                        {% else %}
                            <a href="{% url 'visitor:login' %}?next={{ request.path }}"><b>Espace particuliers</b></a>
                        {% endif %}
                    </li>
                    <li><a href="{% url 'visitor:todo' %}"><b>Espace pro</b></a></li>
                    {% if request.user.is_authenticated %}
                        <li></li>
                    {% else %}
                        <li><a href="{% url 'visitor:inscription' %}?next={{ request.path }}"><b>Inscription</b></a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
        <div id="configuration">
            <div id="log">
                {% if request.user.is_authenticated %}
                    <a href="{% url 'visitor:edit_customer' %}?next={{ request.path }}">
                    {{ request.user.first_name }} {{ request.user.last_name }}</a><br>
                    <a href="{% url 'visitor:logout' %}?next={{ request.path }}">Se déconnecter</a>
                {% else %}
                <a href="{% url 'visitor:login' %}?next={{ request.path }}"><b>Se connecter</b></a>
                {% endif %}
            </div>
            <div id="language">
                <a href="{% url 'visitor:language_choice' %}"><b>FR</b></a>
            </div>
            <div id=calendar_clock>
                <div id="clock">
                    {% now "H:i" %}
                </div>
                <div id="calendar">
                    {% now "l j F Y" %}
                </div>
            </div>
        </div>
    </header>

        {% block content %}{% endblock %}

    <footer class=banner>
        <div class="footer-bloc">
            <h1>Louer</h1>
            <nav class="nav-footer" aria-label="Louer">
                <ul class="nav-column">
                    <li><a href="{% url 'visitor:reservation' %}">Louer une voiture</a></li>
                    <li><a href="{% url 'visitor:todo' %}">Louer un utilitaire</a></li>
                </ul>
            </nav>
        </div>
        <div class="footer-bloc">
            <h1>Espace client</h1>
            <nav class="nav-footer" aria-label="Espace client">
                <ul class="nav-column">
                    <li><a href="{% url 'visitor:booking_management' %}">Gérer vos réservations</a></li>
                    <li><a href="{% url 'visitor:todo' %}">Imprimer une facture</a></li>
                    <li><a href="{% url 'visitor:todo' %}">Conditions générales</a></li>
                </ul>
            </nav>
        </div>
        <div class="footer-bloc">
            <h1>A propos</h1>
            <nav class="nav-footer" aria-label="A propos">
                <ul class="nav-column">
                    <li><a href="{% url 'visitor:todo' %}">Notre entreprise</a></li>
                    <li><a href="{% url 'visitor:agencies' %}">Nos agences</a></li>
                    <li><a href="{% url 'visitor:todo' %}">Nous contacter</a></li>
                    <li><a href="{% url 'visitor:legal_notice' %}">Mentions légales</a></li>
                </ul>
            </nav>
        </div>    
        <div class="footer-block">
            <h1>Suivez nous</h1>
            <div id="social_networks">
                <a href="http://www.facebook.com" title="Suivez nous sur Facebook" target="_blank"><img src="{% static 'visitor/icons/facebook.png' %}" alt="Facebook" /></a>
                <a href="http://www.twitter.com" title="Suivez nous sur Twitter" target="_blank"><img src="{% static 'visitor/icons/twitter.png' %}" alt="Twitter" /></a>
                <a href="http://www.instagram.com" title="Suivez nous sur Instagram" target="_blank"><img src="{% static 'visitor/icons/instagram.png' %}" alt="Instagram" /></a>
            </div>
        </div>
    </footer>
</body>
</html>

superloc/visitor/templates/visitor/edit_customer.html
{% extends "visitor/base.html" %}
{% block title %}Modifier votre compte{% endblock %}
{% block content %}
    <h1>Bonjour {{ request.user.first_name }} {{ request.user.last_name }}</h1>
    <h1>Votre compte :</h1>
    <form method="post" enctype="multipart/form-data">
        {{ user_form.as_p }}
        {{ customer_form.as_p }}
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}"/>
        <p><input type="submit" value="Enregistrer les modifications"></p>
    </form>
{% endblock %}

superloc/visitor/templates/visitor/index.html
{% extends 'visitor/base.html' %}
{% load static %}

{% block title %}SUPERLOC | Location de véhicules de tourisme et utilitaires{% endblock %}

{% block content %}
    <div id="main_content">
        <div id="left_block">
            <div id=null>
            </div>
            <div class="carousel">
                <input type="radio" name="images" id="i1" checked>
                <input type="radio" name="images" id="i2">
                <input type="radio" name="images" id="i3">
                <input type="radio" name="images" id="i4">
                <input type="radio" name="images" id="i5">
                    <div class="carousel_img" id="one">
                        <img src="{% static 'visitor/images/citadine.jpg' %}" alt="Citadine">
                        <figcaption>Louer une citadine</figcaption>
                        <label for="i5" class="pre"></label>
                        <label for="i2" class="nex"></label>
                    </div>
                    <div class="carousel_img" id="two">
                        <img src="{% static 'visitor/images/routiere.jpg' %}" alt="Routière">
                        <figcaption>Louer une routière</figcaption>
                        <label for="i1" class="pre"></label>
                        <label for="i3" class="nex"></label>
                    </div>
                    <div class="carousel_img" id="three">
                        <img src="{% static 'visitor/images/luxe.jpg' %}" alt="Luxe">
                        <figcaption>Louer une voiture de luxe</figcaption>
                        <label for="i2" class="pre"></label>
                        <label for="i4" class="nex"></label>
                    </div>  
                    <div class="carousel_img" id="four">
                        <img src="{% static 'visitor/images/transport.jpg' %}" alt="Transport de personnes">
                        <figcaption>Louer un véhicule de transport de personnes</figcaption>
                        <label for="i3" class="pre"></label>
                        <label for="i5" class="nex"></label>
                    </div>        
                    <div class="carousel_img" id="five">
                        <img src="{% static 'visitor/images/utilitaire.jpg' %}" alt="Utilitaire">
                        <figcaption>Louer un utilitaire</figcaption>
                        <label for="i4" class="pre"></label>
                        <label for="i1" class="nex"></label>
                    </div>
            </div>
        </div>
        <div id="right_block">
            <div id="advertisement">
                <h2>Super Promo !</h2>
                Citadine à partir de 39 € TTC/JOUR<br>
                <img src="{% static 'visitor/images/trois_voitures.jpg' %}" alt="Trois voitures" />
            </div>
            <div id="quick_rent">
                <h2>Louer un véhicule</h2>
                <div id="agence">
                    <form action="{% url 'visitor:agencies' %}">
                        Trouver votre agence
                        <button type="submit">Go !</button>
                    </form>
                </div>
                <form action="{% url 'visitor:todo' %}">
                    <div id="vehicle_choice">
                        Catégorie de véhicule
                        <select id="category" required>
                            <option value="L">L - Compacte automatique</option>
                        </select>
                    </div>
                    <div id ="date_agency">
                        <div id="departure">
                            <div class="date">
                                <label for="date_departure">Départ</label><br>
                                <input type="datetime-local" id="date_departure"
                                name="date_start"
                                min="2022-01-01T00:00" max="2022-12-01T00:00" required>
                            </div>
                            <div class="agency">
                                Agence<br>
                                <select id="agency_departure" required>
                                    <option value="1">Paris - Dauphine</option>
                                </select>
                            </div>
                        </div>
                        <div class="back">
                            <div class="date">
                                <label for="date_back">Retour</label><br>
                                <input type="datetime-local" id="date_back"
                                name="date_back"
                                min="2022-01-01T00:00" max="2022-12-01T00:00" required>
                            </div>
                            <div class="agency">
                                Agence<br>
                                <select id="agency_back" required>
                                    <option value="1">Paris - Dauphine</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div id="book">
                        <input type="submit" value="Réserver !">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

superloc/visitor/templates/visitor/reservation.html
{% extends "visitor/base.html" %}

{% block title %}SUPERLOC | Formulaire de réservation{% endblock %}

{% block content %}
<div>
  <h1>Formulaire de réservation</h1>
  <form action="{% url 'visitor:reservation' %}" method="post">
    {%csrf_token%}
    {{ form.as_p }}
    <input type="submit" value="Réserver">
  </form>
</div>
{% endblock %}

superloc/visitor/templates/visitor/tourism_categories.html
{% extends "./base.html" %}

{% load static %}

{% block title %}Nos véhicules de tourisme{% endblock %}

{% block content %}
<div class="display_categories">
    {% load static %}
    <h1>Nos véhicules de tourisme</h1>
    <div class="categories_strip">
        <div class = "categories">
            {% for category in category_list %}
            <div class="categories_category">
                <img src="{{category.image.url}}" alt="{{category.sample}}" />
                <p><b>{{ category.sample }}</b> ou équivalent</p>
                <a href="{% url 'visitor:tourism_category' category.code %}">Voir détails</a>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

superloc/visitor/templates/visitor/tourism_category.html
{% extends "./base.html" %}

{% load static %}

{% block title %}{{ category.label }}{% endblock %}

{% block content %}
<div id="category">
    <h1 id="category_title">{{ category.label }} - Groupe {{ category.code }} : {{category.sample}} ou équivalent</h1>
    <div id="category_details">
        <img id="category_image" src="{{category.image.url}}" alt="{{category.sample}}"/>
        <div id="category_features">
            <p id="category_description">{{category.description}}</p>
            <table id="features">
                <tbody>
                <tr>
                    <th scope="col">
                        <img title="nbr_place" src="{% static 'visitor/icons/car_details_passengers.png'%}" alt="nbr_places"/>
                    </th>
                    <td>
                        {{category.nb_seats}} places
                    </td>
                    <th scope="col">
                        <img title="nbr_luggage" src="{% static 'visitor/icons/car_details_luggage.png'%}" alt="nbr_valises"/>
                    </th>
                    <td>
                        {{category.nb_luggage}} bagage{{category.nb_luggage|pluralize}}
                    </td>
                    <th scope="col">
                        <img title="nbr_portes" src="{% static 'visitor/icons/car_details_doors.png'%}" alt="nbr_portes"/>
                    </th>
                    <td>
                        {{category.nb_doors}} porte{{category.nb_doors|pluralize}}
                    </td>
                </tr>
                <tr>
                    <th scope="col">
                        <img title="transmission" src="{% static 'visitor/icons/car_details_transmission.png'%}" alt="transmission"/>
                    </th>
                    <td>
                        {{category.get_gear_display}}
                    </td>
                    <th scope="col">
                        <img title="énergie" src="{% static 'visitor/icons/car_details_energy.png'%}" alt="énergie"/>
                    </th>
                    <td>
                        {{category.get_energy_display}}
                    </td>
                    <th scope="col">
                        <img title="climatisation" src="{% static 'visitor/icons/car_details_AC.png'%}" alt="climatisation"/>
                    </th>
                    <td>
                        {% if category.climate_control %}Climatisation
                        {% else %}Pas de climatisation
                        {% endif %}
                    </td>
                </tr>
                </tbody>
            </table>
            <p>Véhicules similaires : {{category.equivalent}}</p>
        </div>
    </div>
    <div id="category_legal">
        <p>Pré-autorisation bancaire : {{category.pre_pay}} € - Ce montant vous sera demandé en agence lors de la prise du véhicule, mais ne sera pas débité de votre compte bancaire sauf en cas de non restituation ou de dégradation du véhicule.</p>
    </div>
</div>
{% endblock %}